VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "testEvent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Dim WithEvents app As Application
Attribute app.VB_VarHelpID = -1
Dim WithEvents Wb As Workbook
Attribute Wb.VB_VarHelpID = -1
Dim WithEvents frm As UserForm
Attribute frm.VB_VarHelpID = -1

Dim WithEvents appwithout As Application
Attribute appwithout.VB_VarHelpID = -1

